Building3D:
  root_dir: './datasets/demo_dataset' # Building3D dataset root dir
  num_points: 5120
  use_color: True
  use_intensity: True
  normalize: True
  augment: True
  use_surface_grouping: True  # Enable surface-aware processing
  use_outlier_removal: True  # Enable outlier removal (can be overridden programmatically)
  
  # Preprocessor Configuration
  preprocessor:
    normalize: True
    use_outlier_removal: True
    use_surface_grouping: True  # Enable advanced processing
    compute_normals: True
    compute_border_weights: True
    
    outlier_params:
      stat_k: 15
      stat_std_ratio: 3.0  # More conservative
      radius_threshold: 0.04
      radius_min_neighbors: 2  # More lenient
      elev_std_ratio: 3.0  # More conservative
      auto_scale_radii: True
    
    grouping_params:
      coarse_params:
        eps: 0.05
        min_samples: 5
        auto_scale_eps: True
      refinement_params:
        merge_distance: 0.05
        min_group_size: 15
    
    weight_params:
      k_neighbors: 25
      normalize_weights: True
      multi_scale: True  # Enable multi-scale analysis
      use_normal_analysis: True
