# Training Configuration
Training:
  # Model configuration
  model:
    input_dim: 5
    k_neighbors: 20
    max_vertices: 64
  
  # Loss function
  loss:
    use_hungarian: False  # true for hungarian matching, false for MSE
    coord_weight: 10.0
    existence_weight: 1.0
  
  # Optimizer
  optimizer:
    type: 'AdamW'
    lr: 0.001
    weight_decay: 0.0001
  
  # Scheduler
  scheduler:
    type: 'CosineAnnealingLR'
    T_max: 1000
    eta_min: 0.00005
  
  # Training loop
  num_epochs: 1000
  gradient_clip_norm: 1.0

# Dataset Configuration
Building3D:
  root_dir: './datasets/demo_dataset' # Building3D dataset root dir
  num_points: 2560
  use_color: True
  use_intensity: True
  augment: False
  
  # Preprocessor Configuration
  preprocessor:
    normalize: True
    use_outlier_removal: False
    use_surface_grouping: True
    compute_border_weights: True  
    cache_dir: 'datasets/preprocessed'  # Preprocessed data cache directory
    
    outlier_params:
      stat_k: 15
      stat_std_ratio: 3.0 
      radius_threshold: 0.04
      radius_min_neighbors: 2 
      elev_std_ratio: 3.0 
      auto_scale_radii: True
    
    grouping_params:
      coarse_params:
        eps: 0.05
        min_samples: 5
        auto_scale_eps: True
      refinement_params:
        merge_distance: 0.05
        min_group_size: 15
      
      # Default processing parameters for all spatial clusters
      default_processing:
        outlier_removal:
          stat_k: 12
          stat_std_ratio: 3.5
          radius_threshold: 0.03
          radius_min_neighbors: 2
          auto_scale_radius_param: True
        normal_computation:
          base_k_neighbors: 12
          curvature_threshold: 0.1
          smooth_iterations: 1
          smooth_radius: 0.04
          adaptive_k: True
    
    weight_params:
      k_neighbors: 25
      normalize_weights: True
      multi_scale: True  
      use_normal_analysis: True